
server:
  port: ${PORT:8091}

spring:
  data:
    mongodb:
      user: appdbuser123
      password: appdbuser123
      uri: mongodb+srv://admin:admin@cluster.chgn7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority